spring.application.name=backend
# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE (NEON POSTGRES)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-dry-tree-amr2p0g7-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_q8oLD3HKmZYJ
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONNECTION POOL (optional but good)
# ===============================
spring.datasource.hikari.maximum-pool-size=5

# ===============================
# LOGGING (optional)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE